[workspace]
members = [
    "c-callback",
]

[workspace.dependencies]
kriswuollett-examples-c-callback = { path = "c-callback" }
cbindgen = "0.24.3"
tokio = { version = "1.29.1", features = ["full"] }
