[package]
name = "kriswuollett_examples_c_callback"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
tokio = { version = "1.29.1", features = ["full"] }

[build-dependencies]
cbindgen = "0.24.3"
